### ISSUE TITLE
Epic: Basic HPACK Implementation

### ISSUE THREAD

**Issue by DrkWithT** [DrkWithT/SacHacks-DerksGroup-Project#6]
As a web server programmer, I want to implement a working portion of the HPACK compression scheme for HTTP/2 so that later header encoding and decoding is acceptable by clients such as _cURL_.

**Children Items:**
- [ ] TechFeature: Huffman Coding Utilities
- [ ] TechFeature: Header Indexing Table
- [ ] TechFeature: Integer & String Utilities
